First big batch of instructions skeletons
riscv-software-src/riscv-unified-db pull request #138
Opened 2024-10-18 15:51 UTC by AFOliveira

This PR has the instructions skeletons of the following extension:
- Zicfiss
- Zifencei
- H
- Zabha
- Zacas
- Zalasr
- Zawrs
- Zfbfmin
- Zicond

Q and D are also almost ready but I am modifying registers naming.

2024-10-18 15:58 UTC, AFOliveira commented
Regression test passed locally, I might have added some folder by mistake, I'll try to fix it asap.

2024-10-18 16:00 UTC, dhower-qc requested changes
In general, it seems that every skeleton sets data_independent_timing to true, correct? Could you change that to false? I think that will make it easier to get the correct list in later.

2024-10-18 20:54 UTC, AFOliveira commented on arch/inst/H/hinval.gvma.yaml
> In general, it seems that every skeleton sets data_independent_timing to true, correct? Could you change that to false? I think that will make it easier to get the correct list in later.

Of course, will do so now.

>hinval.gvma.yaml is already in the db (under Svinal)

I added on mistake, I think that's what broke the regression test

2024-10-18 20:58 UTC, AFOliveira commented on arch/inst/Zifencei/fence.i.yaml
@dhower-qc  I'm not sure I fully understood this, is it for the fence only or for all instructions?

2024-10-18 21:04 UTC, AFOliveira commented on arch/inst/Zifencei/fence.i.yaml
Oh, sorry, I didn't notice that. I was trying not to mess with any of the already existing instructions, I'll fix that right now.

2024-10-18 21:41 UTC, AFOliveira commented
@dhower-qc  This is related to fence.i not having the parameter "variables", there was none on yours, but I guess now it's breaking the validation. Shall I add an empty "variables" field?
```
Parsing IDL code for RV64...done
Type checking IDL code for _64...

Instructions: |================================================================|

CSRs: |========================================================================|

Functions: |===================================================================|
/home/runner/work/riscv-unified-db/riscv-unified-db/lib/validate.rb:239:in `block in validate_instruction_encoding': undefined method `count' for nil:NilClass (NoMethodError)

        vars_match = variables.count { |variable| ary_from_location(variable["location"]).include?(i) }
                              ^^^^^^
	from /home/runner/work/riscv-unified-db/riscv-unified-db/lib/validate.rb:236:in `times'

```

2024-10-18 22:25 UTC, AFOliveira commented
Everything should now be ready.

2024-10-20 15:23 UTC, dhower-qc approved these changes
Thanks!!

2024-10-20 15:23 UTC, merged