Fix definedBy on some instructions
riscv-software-src/riscv-unified-db pull request #340
Opened 2024-12-04 17:30 UTC by AFOliveira

As caught and reported by @ThinkOpenly. Solves #319 . Solves #322 .

2024-12-10 20:55 UTC, AFOliveira commented
@dhower-qc is this also repeated from what you did on #350? If so I guess we can just close it.

2024-12-17 23:03 UTC, dhower-qc commented
Fixed in #350

2024-12-19 16:23 UTC, AFOliveira commented
#362 Explains what happened here, I'll fix this PR.

2025-01-08 17:51 UTC, dhower-qc requested changes

2025-01-08 17:51 UTC, dhower-qc commented on arch/inst/Zfh/fleq.h.yaml
> -  anyOf: [Zfa, Zfh]
Shouldn't this remain anyOf?

2025-01-08 17:51 UTC, dhower-qc commented on arch/inst/Zfh/flh.yaml
> +  allOf: [Zfh, Zfhmin]
And this one

2025-01-08 17:51 UTC, dhower-qc commented on arch/inst/Zfh/fmv.x.h.yaml
> +  allOf: [Zfh, Zfhmin]
And this one

2025-01-08 17:51 UTC, dhower-qc commented on arch/inst/Zfh/fsh.yaml
> +  allOf: [Zfh, Zfhmin]
And this one

2025-01-08 17:57 UTC, ThinkOpenly commented on arch/inst/Zfh/fleq.h.yaml
> -  anyOf: [Zfa, Zfh]
This should actually be "allOf", no?

2025-01-08 18:01 UTC, dhower-qc commented on arch/inst/Zfh/fleq.h.yaml
> -  anyOf: [Zfa, Zfh]
yes, my bad. I was trying to mark all the [Zfh, Zfhmin] combos. I must have fat fingers...

2025-01-08 18:07 UTC, ThinkOpenly commented on arch/inst/Zfh/flh.yaml
> +  allOf: [Zfh, Zfhmin]
There is some weirdness with `flh` and the "Zhinx" extension, but I guess we don't include that extension yet.

2025-01-08 18:08 UTC, ThinkOpenly commented on arch/inst/Zfh/fmv.x.h.yaml
> +  allOf: [Zfh, Zfhmin]
Same "Zhinx" weirdness here.

2025-01-08 18:09 UTC, ThinkOpenly commented on arch/inst/Zfh/fsh.yaml
> +  allOf: [Zfh, Zfhmin]
Same "Zhinx" weirdness here.

2025-01-09 14:11 UTC, AFOliveira commented on arch/inst/Zfh/flh.yaml
> +  allOf: [Zfh, Zfhmin]
should I then keep them or leave them?
I actually couldn't find specific information on this is the ISA and riscv-opcodes doesn't even define zfhmin.

2025-01-09 14:17 UTC, dhower-qc commented on arch/inst/Zfh/flh.yaml
> +  allOf: [Zfh, Zfhmin]
We should keep Zfhmin, but it should be `anyof: [Zfh, Zfhmin]`, since either extension will define `flh` (doesn't require *both* `Zfh` and `Zfhmin`)

Re: @ThinkOpenly's comment on `Zhinx`: Good point. I guess this really should be "anyOf: [Zfh, Zfhmin, Zhinx]", with the `operation()`/`sail()` choosing which version to implement.

2025-01-09 16:22 UTC, AFOliveira commented on arch/inst/Zfh/flh.yaml
> +  allOf: [Zfh, Zfhmin]
Added all 3.

2025-01-10 10:28 UTC, AFOliveira commented
There is an error with missing Zhinx extension:
Should I 
- add Zhinx as an extension to the UDB under the arch/ext folder?
- drop the Zhinx from this PR instructions?

2025-01-10 13:28 UTC, dhower-qc commented
Go ahead and add Zhinx, with a new issue to remind us that Zhinx is not implemented (since a simple look for empty operation() won't catch it)

2025-01-10 18:46 UTC, AFOliveira commented
@dhower-qc Done!

2025-01-12 19:15 UTC, ThinkOpenly commented on arch/ext/Zhinx.yaml
> +  `x` registers in Zhinx.
In the commit that adds this content, could you describe where the content originated?
Also, remove the "Signed-off-by" line.

2025-01-13 09:40 UTC, AFOliveira commented on arch/ext/Zhinx.yaml
> +  `x` registers in Zhinx.
Done

2025-01-14 15:30 UTC, dhower-qc approved these changes

2025-01-14 15:52 UTC, AFOliveira commented on arch/ext/Zhinx.yaml
> +  `x` registers in Zhinx.
Since this is more of global to the repository than to my PR I'll still merge to main and in the future we can sort it with the rest of information of the same kind.

2025-01-14 15:52 UTC, merged